name: Metrics
on:
  schedule: [{ cron: "0 */12 * * *" }]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        env:
          METRICS_DEBUG: true
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          PUPPETEER_EXECUTABLE_PATH: google-chrome-stable
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: faiznau94
          template: classic
          base: header
          filename: github-metrics.svg

          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 0
          plugin_activity_filter: pr
          plugin_activity_visibility: public
          plugin_activity_timestamps: true
