name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: faizanu94
          template: classic
          base: header
          filename: github-metrics.svg
          config_timezone: America/Vancouver

          plugin_activity: yes
          plugin_activity_limit: 1000          # max allowed
          plugin_activity_days: 30             # last 30 days
          plugin_activity_filter: pr           # pull requests only
          plugin_activity_visibility: public   # only public repos
          plugin_activity_timestamps: true     # show timestamps
          plugin_activity_ignored: "github-actions[bot],dependabot[bot]"
