name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@3.33.0
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: faizanu94
          template: classic
          base: header
          filename: github-metrics.svg
          config_timezone: America/Vancouver

          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 0
          plugin_activity_filter: "pr,issue"
          plugin_activity_visibility: public
          plugin_activity_timestamps: true
          plugin_activity_ignored: "github-actions[bot],dependabot[bot]"
