name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: faizanu94
          template: classic
          base: header

          filename: github-metrics.svg

          plugin_activity: yes
          plugin_activity_limit: 1000
          plugin_activity_load: 300
          plugin_activity_days: 30
          plugin_activity_filter: pr
          plugin_activity_visibility: public
          plugin_activity_timestamps: true
          plugin_activity_ignored: "github-actions[bot],dependabot[bot]"
