name: Recent activity
on:
  schedule: [{ cron: "0 0 * * *" }] # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: faizanu94
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 1000       # max per docs
          plugin_activity_load: 300         # default safe load window
          plugin_activity_days: 30          # last 30 days
          plugin_activity_filter: pr        # only PRs
          plugin_activity_visibility: public
          plugin_activity_timestamps: true
          plugin_activity_ignored: "github-actions[bot],dependabot[bot]"
